FROM node:20

# set working directory
WORKDIR /app

# copy project files
COPY . .

# install dependencies
RUN npm install

# build typescript (if needed)
RUN npx tsc

# run your test
CMD ["node", "dist/index.js"]